In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os 
import shutil

In [9]:
FILE_PATH="Positive_github/metadata.csv"
df=pd.read_csv(FILE_PATH)

In [10]:
df.shape

(877, 29)

In [11]:
df.head()

,patientid,offset,sex,age,finding,RT_PCR_positive,survival,intubated,intubation_present,went_icu,...,modality,date,location,folder,filename,doi,url,license,clinical_notes,other_notes
0,2,0.0,M,65.0,COVID-19,Y,Y,N,N,N,...,X-ray,"January 22, 2020","Cho Ray Hospital, Ho Chi Minh City, Vietnam",images,auntminnie-a-2020_01_28_23_51_6665_2020_01_28_...,10.1056/nejmc2001272,https://www.nejm.org/doi/full/10.1056/NEJMc200...,NaN,"On January 22, 2020, a 65-year-old man with a ...",NaN
1,2,3.0,M,65.0,COVID-19,Y,Y,N,N,N,...,X-ray,"January 25, 2020","Cho Ray Hospital, Ho Chi Minh City, Vietnam",images,auntminnie-b-2020_01_28_23_51_6665_2020_01_28_...,10.1056/nejmc2001272,https://www.nejm.org/doi/full/10.1056/NEJMc200...,NaN,"On January 22, 2020, a 65-year-old man with a ...",NaN
2,2,5.0,M,65.0,COVID-19,Y,Y,N,N,N,...,X-ray,"January 27, 2020","Cho Ray Hospital, Ho Chi Minh City, Vietnam",images,auntminnie-c-2020_01_28_23_51_6665_2020_01_28_...,10.1056/nejmc2001272,https://www.nejm.org/doi/full/10.1056/NEJMc200...,NaN,"On January 22, 2020, a 65-year-old man with a ...",NaN
3,2,6.0,M,65.0,COVID-19,Y,Y,N,N,N,...,X-ray,"January 28, 2020","Cho Ray Hospital, Ho Chi Minh City, Vietnam",images,auntminnie-d-2020_01_28_23_51_6665_2020_01_28_...,10.1056/nejmc2001272,https://www.nejm.org/doi/full/10.1056/NEJMc200...,NaN,"On January 22, 2020, a 65-year-old man with a ...",NaN
4,4,0.0,F,52.0,COVID-19,Y,NaN,N,N,N,...,X-ray,"January 25, 2020","Changhua Christian Hospital, Changhua City, Ta...",images,nejmc2001573_f1a.jpeg,10.1056/NEJMc2001573,https://www.nejm.org/doi/full/10.1056/NEJMc200...,NaN,diffuse infiltrates in the bilateral lower lungs,NaN

In [6]:
TARGET_DIR="dataset/covid"
if not os.path.exists(TARGET_DIR):
    os.mkdir(TARGET_DIR)

In [12]:
count=0
for (i,row) in df.iterrows():
    if(row['finding']=="COVID-19" and row["view"]=="PA"):
        count+=1
        filename=row["filename"]
        image_path=os.path.join(IMAGES_PATH,filename)
        image_copy_path=os.path.join(TARGET_DIR,filename)
        shutil.copy2(image_path,image_copy_path)

In [13]:
print(count)

180

In [14]:
import random
KAGGLE_FILE_PATH="Kaggle/train/NORMAL"
TARGET_NORMAL_DIR="dataset/Normal"

In [15]:
images_names=os.listdir(KAGGLE_FILE_PATH)

In [16]:
random.shuffle(images_names)

In [17]:
for i in range(180):
    image_name=images_names[i]
    image_path=os.path.join(KAGGLE_FILE_PATH,image_name)
    target_path=os.path.join(TARGET_NORMAL_DIR,image_name)
    shutil.copy2(image_path,target_path)

In [12]:
df.describe()

,offset,age,temperature,pO2_saturation,leukocyte_count,neutrophil_count,lymphocyte_count
count,666.000000,645.000000,74.000000,119.000000,16.000000,28.000000,37.000000
mean,8.749249,53.713178,38.933784,78.475630,5.024375,5.307143,4.965459
std,32.027083,16.691852,6.667120,38.742573,2.660341,3.489956,21.354733
min,-360.000000,20.000000,36.000000,20.000000,0.220000,0.000000,0.400000
25%,1.000000,40.000000,37.725000,55.000000,3.067500,2.725000,0.800000
50%,5.000000,54.000000,38.200000,85.000000,4.745000,4.800000,1.100000
75%,10.000000,67.000000,38.975000,95.000000,6.857500,6.925000,1.600000
max,365.000000,94.000000,95.000000,340.000000,11.200000,12.900000,131.000000